#!/usr/bin/python

from cli import *
import yaml
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("-d", "--debug", help="Debug Mode", action="store_true")
parser.add_argument("-j", "--json", help="JSON output mode", action="store_true")
parser.add_argument("-c", "--color", help="COLOR output mode", action="store_true")
parser.add_argument("-C", "--config", help="Config file path [default mnavigator.yaml]", default="mnavigator.yaml", action="store")
parser.add_argument("-p", "--path", help="Metadata PATH for pipe output mode [Disables INTERATIVE mode][DEFAULT ROOT]",nargs='?', const="/")

args=parser.parse_args()

with open(args.config,'r') as ymlfile:
    cfg = yaml.load(ymlfile)

if args.debug or cfg['debug']:
    setdebugstatus(True)
    print "ARGUMENTS: ",args
    for key, value in cfg.items():
        print key, value

if args.json or cfg['jsonenable']:
    setjsonstatus()

if args.color or cfg['colorenable']:
    setcolorstatus()

if args.path:
   pipemode=True
   pipemodepath=args.path
else:
   pipemode=False
   pipemodepath=None

setconfig(cfg)
climode(pipemode, pipemodepath)
